'use client';
import {useEffect,useState} from 'react';
import {Building2,Search,RotateCcw,ArrowUpRight,Download,Map,Box,Database,ChevronRight,Mountain} from 'lucide-react';
import {useCampusTools} from '@/hooks/use-campus-tools';
import {assetPath} from '@/lib/runtime-mode';
import LiveConnection from '@/components/live-connection';
import {type ConnectorSession} from '@/lib/local-connector';
import EnergyPanel from '@/components/energy-panel';
import CampusViewer from '@/components/campus-viewer';
import {Switch} from '@/components/ui/switch';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import type {Campus} from '@/lib/campus-types';
export default function Home(){
 const [campus,setCampus]=useState<Campus|null>(null),[error,setError]=useState(''),[selected,setSelected]=useState('sfu-55'),[query,setQuery]=useState(''),[aerial,setAerial]=useState(true),[context,setContext]=useState(true),[view,setView]=useState('orbit'),[reset,setReset]=useState(0);
 useEffect(()=>{fetch(assetPath('data/campus.json')).then(r=>{if(!r.ok)throw Error('Campus data unavailable');return r.json() as Promise<Campus>}).then(setCampus).catch(e=>setError(e.message));},[]);
 useCampusTools(campus,setSelected);
 const [session,setSession]=useState<ConnectorSession|null>(null),[connectionMessage,setConnectionMessage]=useState('');
 const updateSession=(next:ConnectorSession|null)=>{setSession(next);setConnectionMessage('');};
 const expireSession=()=>{setSession(null);setConnectionMessage('Your connection has ended. Pair this tab again to resume live readings.');};
 const building=campus?.buildings.find(b=>b.id===selected);const visible=campus?.buildings.filter(b=>b.source==='sfu'&&(b.name+' '+b.abbr+' '+b.buildingCode).toLowerCase().includes(query.toLowerCase()))||[];
 return <main className="twin-app"><header className="topbar"><div className="brand"><img className="sfu-mark" src={assetPath('brand/SFU_block_colour_rgb_1000px.png')} alt="Simon Fraser University" width={1000} height={500}/><div><strong>Burnaby<span className="brand-separator">/</span>Campus twin</strong><small>SIMON FRASER UNIVERSITY · EXPLORATORY MODEL</small></div></div><div className="top-actions"><span className="status-badge"><i/> {session?'Local connector paired':'Campus model · live data disconnected'}</span><a className="quiet-button" href={assetPath('data/sfu-burnaby.glb')} download><Download size={16}/> Export model</a></div></header>
 <div className="workspace"><aside className="asset-panel"><div className="panel-heading"><div><span className="eyebrow">CAMPUS EXPLORER</span><h1>Buildings</h1></div><span className="count">{campus?.stats.campusFeatures??'—'}</span></div><label className="search"><Search size={17}/><input placeholder="Find a building or code…" aria-label="Find a building" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="asset-summary"><span>SFU building registry</span><span>{visible.length} features</span></div><div className="asset-list">{visible.map(b=><button key={b.id} className={'asset-row '+(selected===b.id?'selected':'')} onClick={()=>setSelected(b.id)}><span className="building-icon"><Building2 size={17}/></span><span><strong>{b.name}</strong><small>{b.abbr} · {b.buildingCode}</small></span><ChevronRight size={14}/></button>)}{query&&!visible.length&&<p className="empty">No matching campus buildings.</p>}{error&&<p className="empty" role="alert">{error}</p>}</div><div className="registry-note"><Database size={16}/><span>Official SFU footprints<br/><small>Retrieved September 5, 2026</small></span></div></aside>
 <section className="model-panel" aria-label="3D campus model"><div className="scene-heading"><span className="eyebrow">BURNABY MOUNTAIN</span><h2>A campus, in context.</h2><p>49.279° N &nbsp; 122.919° W</p></div>{campus?<CampusViewer campus={campus} selected={selected} onSelect={setSelected} aerial={aerial} context={context} view={view} reset={reset}/>:<div className="model-loading">{error||'Loading campus geometry…'}</div>}<div className="scene-tools"><button className={view==='orbit'?'active':''} onClick={()=>setView('orbit')}><Box size={16}/>3D</button><button className={view==='plan'?'active':''} onClick={()=>setView('plan')}><Map size={16}/>Plan</button><button title="Reset campus view" aria-label="Reset campus view" onClick={()=>setReset(n=>n+1)}><RotateCcw size={16}/></button></div><div className="scene-footer"><span>Drag to orbit · Scroll to zoom · Right-drag to pan</span><span>Flat-roof massing · True horizontal scale</span></div></section>
 <aside className="details-panel"><Tabs defaultValue="inspect"><TabsList className="inspector-tabs"><TabsTrigger value="inspect">Inspect</TabsTrigger><TabsTrigger value="layers">Layers & sources</TabsTrigger></TabsList><TabsContent value="inspect"><div className="inspector-content"><span className="eyebrow">{building?'SELECTED BUILDING':'CAMPUS OPERATIONS'}</span><h2>{building?.name||'Connect place to performance.'}</h2><p className="muted">{building?`${building.abbr} · Building ${building.buildingCode||'unassigned'}`:'Select a building to inspect its geometry and source information.'}</p><div className="metric-grid"><div><small>{building?'Footprint':'Campus features'}</small><strong>{building?building.areaM2.toLocaleString():campus?.stats.campusFeatures??'—'}<em>{building?'m²':''}</em></strong></div><div><small>{building?'Model height':'Context features'}</small><strong>{building?building.heightM:campus?.stats.contextFeatures??'—'}<em>{building?'m':''}</em></strong></div></div>{building&&<div className="data-note"><Mountain size={17}/><span>{building.heightStatus}<small>Ground {building.groundM} m · contour-derived</small></span></div>}<LiveConnection session={session} onChange={updateSession} message={connectionMessage}/>{session&&<EnergyPanel key={session.token+building?.buildingCode} building={building} session={session} onSessionEnded={expireSession}/>}<div className="quality-note"><span className="eyebrow">MODEL CONFIDENCE</span><p>Official footprints. Interpolated terrain. Approximate heights. Roof details and façades need LiDAR or BIM.</p></div></div></TabsContent><TabsContent value="layers"><div className="inspector-content"><span className="eyebrow">SCENE LAYERS</span><h2>Grounded in source data.</h2><label className="layer-row"><span><strong>Aerial imagery</strong><small>City of Burnaby · 2025</small></span><Switch checked={aerial} onCheckedChange={setAerial}/></label><label className="layer-row"><span><strong>Surrounding buildings</strong><small>Burnaby open data</small></span><Switch checked={context} onCheckedChange={setContext}/></label><div className="source-links"><a href="https://www.sfu.ca/fs/campus-maps/mapping-services.html" target="_blank" rel="noreferrer">SFU mapping services<ArrowUpRight size={16}/></a><a href="https://viewsfu.its.sfu.ca/apps/vertisee/public/" target="_blank" rel="noreferrer">Working ViewSFU map<ArrowUpRight size={16}/></a><a href={assetPath('data/sources.json')} target="_blank">Source manifest<ArrowUpRight size={16}/></a></div><div className="quality-note"><h3>Geometry limitations</h3>{campus?.limitations.map(s=><p key={s}>{s}</p>)}</div></div></TabsContent></Tabs></aside></div><footer className="bottom-bar"><span><span className="live-dot"/> {session?'Private data connection · this browser only':'Public campus geometry'}</span><span>SFU Facilities Services · Contains information licensed under the Open Government Licence – City of Burnaby</span></footer></main>;
}
