import assert from 'node:assert/strict';
import fs from 'node:fs';
import * as THREE from 'three';
import {createCampusModel} from '../lib/model.ts';
import {parseReading} from '../lib/energy.ts';
const campus=JSON.parse(fs.readFileSync('public/data/campus.json'));
const terrain=JSON.parse(fs.readFileSync('public/data/terrain.json'));
assert.equal(new Set(campus.buildings.map(b=>b.id)).size,campus.buildings.length);
assert.equal(terrain.heights.length,terrain.width*terrain.depth);
assert(terrain.heights.every(Number.isFinite));
assert(campus.buildings.every(b=>b.center.every(Number.isFinite)&&b.heightM>0));
assert.equal(campus.buildings.filter(b=>b.source==='sfu').length,77);
const aq=campus.buildings.find(b=>b.abbr==='AQ');assert(aq.polygons.some(p=>p.length>1),'AQ courtyard must remain a hole');
const {root,land}=createCampusModel(campus,terrain);root.updateMatrixWorld(true);
assert.equal(land.geometry.attributes.position.count,terrain.heights.length);
assert.equal(land.geometry.attributes.position.getY(0),Math.fround(terrain.heights[0]-terrain.origin[2]));
let triangles=0;root.traverse(o=>{if(o instanceof THREE.Mesh){const p=o.geometry.attributes.position;for(let i=0;i<p.count;i++)assert([p.getX(i),p.getY(i),p.getZ(i)].every(Number.isFinite));triangles+=(o.geometry.index?.count||p.count)/3;}});
const stamp='2026-09-05T15:00:00Z';const p={value:'91.4',state:'Normal',disabled:'0',device:'meter',name:'M_kW Total',units:'kW'};
assert.equal(parseReading(1,'meter',p,stamp).value,91.4);
for(const bad of ['No Value','','n','Infinity','1e309'])assert.equal(parseReading(1,'meter',{...p,value:bad},stamp).value,null);
assert.equal(parseReading(1,'meter',{...p,value:'0'},stamp).value,0);
assert.equal(parseReading(1,'meter',{...p,device:'wrong'},stamp).quality,'unavailable');
assert.equal(parseReading(1,'meter',{...p,units:'kWh'},stamp).value,null);
assert.equal(parseReading(1,'meter',{...p,state:'Disabled'},stamp).quality,'flagged');
assert.equal(parseReading(1,'meter',p,stamp).sampledAt,null);
const glb=fs.readFileSync('public/data/sfu-burnaby.glb');assert.equal(glb.toString('ascii',0,4),'glTF');assert.equal(glb.readUInt32LE(4),2);assert.equal(glb.readUInt32LE(8),glb.length);
const len=glb.readUInt32LE(12);const doc=JSON.parse(glb.toString('utf8',20,20+len));assert(doc.meshes.length>200);assert(doc.nodes.some(n=>n.extras?.crs==='EPSG:26910'));
console.log(`Verified ${campus.buildings.length} model features, ${triangles} triangles, AQ courtyard preservation, finite terrain, GLB structure, and meter quality/missing-value handling.`);
